os:
  - linux

matrix:
  include:
    - name: "checkTomls"
      env: TEST_COMMAND="./checkTomls.bash"

    - name: "travisScript"
      env: TEST_COMMAND="./util/travisScript.bash"

    - name: "searchRankScript"
      env: TEST_COMMAND="./util/searchRankScript.bash"

script:
  - (eval "$TEST_COMMAND")
