[brick]
name = "GPUIterator"
version = "0.1.0"
chplVersion = "1.16.0..1.20.0"
authors = ["Akihiro Hayashi", "Sri Raj Paul", "Vivek Sarkar"]
source = "https://github.com/ahayashi/chapel-gpu"

[dependencies]
