name: Mason Registry CI
on:
  pull_request: 
    paths:
      - 'Bricks/**'
jobs:
  check_tomlfiles:
    name: Check TOML Files
    runs-on: ubuntu-latest
    steps:
      - name: Run check toml file script
        shell: bash 
        run: |
          echo "Testing this out"


