name: Mason Registry CI
on:
  pull_request: 
    paths:
      - 'Bricks/**'
jobs:
  checks_for_package:
    name: Check Package 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run checkTomlScript
        run: |
					cd Bricks 
					func() {
							DIR=$1
							if [[ $DIR != "." && $DIR != '..' ]]; then   
									if ls $DIR/*.toml &>/dev/null
									then
											echo "Found toml for $DIR"
									else
											exit 1
									fi
							fi
					}


					ls -f  | while read -r file; do func $file; done 

