name: Mason Registry CI
on:
  pull_request: 
    paths-ignore:
      - 'searchRankScript.bash'
      - 'travisScript.bash'
      - 'checkTomls.bash'
    paths:
      - 'Bricks/**'
jobs:
  check_tomlfiles:
    name: Check TOML Files
    runs-on: ubuntu-latest
    steps:
      -name: Run check toml file script
       run: bash checkTomls.bash


