name: Mason Search Ranking Script
on:
  pull_request:
    types:
      - closed
      - opened
      - synchronize

jobs:
  run_script_on_merge:
    name: Run search script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 4
      - name: Run script on PR merge
        if: github.event.pull_request.merged == true
        shell: bash
        env: 
          PASSWORD: ${{ secrets.PASSWORD }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          echo "$USERNAME"
          bash ./util/searchRankScript.bash
